In [2]:
from  tom_starread import tom_starread
from tom_extractData import tom_extractData

In [3]:
star_data = tom_starread("./all_particles_15-11-2019.star")
star_data

rlnMicrographName  rlnCoordinateX  rlnCoordinateY  rlnCoordinateZ  \
0               101.mrc         329.889         343.124        1012.450   
1               101.mrc         793.889         655.077         941.163   
2               101.mrc        2685.125         368.587        1031.393   
3               101.mrc        2642.635        3348.587         530.373   
4               101.mrc        3061.567        2973.125         527.113   
...                 ...             ...             ...             ...   
11542           118.mrc        2039.510        1908.290         617.047   
11543           118.mrc        1720.395         712.510         866.037   
11544           118.mrc        2479.510        1680.628         602.817   
11545           118.mrc        2301.510        2184.953         948.372   
11546           118.mrc         658.510         756.628         875.847   

       rlnAngleRot  rlnAngleTilt  rlnAnglePsi  rlnMagnification  \
0       -48.993990     15.492610   -76.451680           10000.0   
1      -101.747780     85.299932   160.948385           10000.0   
2       -55.913580    106.104003   110.741103           10000.0   
3       -80.834630     61.978194     5.846171           10000.0   
4      -128.418870    141.895437   -14.716250           10000.0   
...            ...           ...          ...               ...   
11542   171.252920     83.649823   -31.580720           10000.0   
11543    -4.064220     38.344906    57.374594           10000.0   
11544   130.349468     65.788786    25.393269           10000.0   
11545    70.679554     84.747167  -148.004030           10000.0   
11546   -54.347140     72.633985  -173.056180           10000.0   

       rlnDetectorPixelSize  rlnCtfMaxResolution  ... rlnGroupNumber  \
0                      3.42                  9.7  ...              1   
1                      3.42                  9.7  ...              1   
2                      3.42                  9.7  ...              1   
3                      3.42                  9.7  ...              1   
4                      3.42                  9.7  ...              1   
...                     ...                  ...  ...            ...   
11542                  3.42                  7.1  ...             18   
11543                  3.42                  7.1  ...             18   
11544                  3.42                  7.1  ...             18   
11545                  3.42                  7.1  ...             18   
11546                  3.42                  7.1  ...             18   

      rlnClassNumber  rlnNormCorrection  rlnRandomSubset  \
0                  1                1.0                1   
1                  1                1.0                1   
2                  1                1.0                1   
3                  1                1.0                1   
4                  1                1.0                1   
...              ...                ...              ...   
11542              5                1.0                1   
11543              5                1.0                1   
11544              5                1.0                1   
11545              5                1.0                2   
11546              5                1.0                1   

       rlnLogLikeliContribution  rlnMaxValueProbDistribution  \
0                    15293440.0                     0.807994   
1                    15273660.0                     0.517087   
2                    15246000.0                     0.733273   
3                    15259190.0                     0.605896   
4                    15260650.0                     0.953581   
...                         ...                          ...   
11542                15307300.0                     0.049497   
11543                15275500.0                     0.091213   
11544                15272540.0                     0.042054   
11545                15312430.0                     0.085835   
11546     

In [ ]:
np.s

In [4]:
st = tom_extractData(star_data,0)

Finish generating st file from relionStar


In [4]:
st

{'p1': {'positions': array([[ 329.889,  343.124, 1012.45 ],
         [ 793.889,  655.077,  941.163],
         [2685.125,  368.587, 1031.393],
         ...,
         [2479.51 , 1680.628,  602.817],
         [2301.51 , 2184.953,  948.372],
         [ 658.51 ,  756.628,  875.847]]), 'angles': array([[ 138,  -13,   15],
         [-168,  109,   85],
         [ 145,  159,  106],
         ...,
         [ -40, -115,   65],
         [  19,   58,   84],
         [ 144,   83,   72]]), 'classes': array([1, 1, 1, ..., 5, 5, 5], dtype=int64), 'tomoName': array(['101.mrc', '101.mrc', '101.mrc', ..., '118.mrc', '118.mrc',
         '118.mrc'], dtype=object), 'psfs': array(['../tilts/subtomo_ribo/new_ctf/101/101_0000044_ctf_3.42A.mrc',
         '../tilts/subtomo_ribo/new_ctf/101/101_0000121_ctf_3.42A.mrc',
         '../tilts/subtomo_ribo/new_ctf/101/101_0000174_ctf_3.42A.mrc', ...,
         '../tilts/subtomo_ribo/new_ctf/118/118_0001524_ctf_3.42A.mrc',
         '../tilts/subtomo_ribo/new_ctf/118/118_000

In [13]:
import numpy as np
#from calcTransforms import *

def tom_calcTransforms(posAng,  maxDist, tomoNames='', dmetric='exact', outputName='', verbose=1, worker_n = 1):
    '''
    TOM_CALCTRANSFORMS calcutes pair transformations for all combinations use
    pruneRad(maxDist) to reduce calc (particles with distance > maxDist will not paired)

    transList=tom_calcTransforms(pos,pruneRad,dmetric,verbose)

    PARAMETERS

    INPUT
        posAng              positions and angles of particles/observation nx6 or List .star               
        maxDist             (inf) max particle/observation distance 
                                  pairs above this distance will be discarted
                                  usually a good value is 2.5 particleRad 
        tomoNames           ('') tuple with tomogramName to seperate tomograms
        dmetric             ('exact') at the moment only exact implemented
        outputName          ('') name of pair output starFile 
        verbose             (1) verbose flag use 0 for no output


    OUTPUT
        starSt          star struck  containing the transformations and input Data


    EXAMPLE
    
        datMat = tom_calcTransforms([0 0 0;1 1 1;2 2 2],[0 0 0; 0 0 10; 10 20 30],10,verbose = 0);

    REFERENCES
    
    '''
    oriPartList = 'noListStarGiven'
    type_posAng = type(posAng)
    if type_posAng.__name__ == 'str':
        oriPartList = posAng
        posAng = tom_starread(posAng)
    if type_posAng.__name__ == 'dict':
        if "pairTransVectX" in posAng.keys():
            print("The file already has transformation information!")
            return 
    # read the star file into a dict/st
    st = tom_extract(posAng,0)
    uTomoId = np.unique(st["label"]["tomoID"])
    uTomoNames = np.unique(st["label"]["tomoName"])
    len_tomo = len(uTomoId)
    #transDict: store the information of transformation
    #allTomoNames: the name of tomo
    #idxOffset: 
    transList = [ ] 
    allTomoNames = [ ]
    idxOffSet = 0
    
    #using multiple process to do calcTransforms
    n_cpu = mp.cpu_count()
    if n_cpu < worker_n:
        print("Warning: %d cpu detected, but %d cpu to be push"%(n_cpu, worker_n))
        worker_n = n_cpu
    
    for i in range(len_tomo):
        idx = np.where(st["label"]["tomoID"] == uTomoId[i])
        posAct = st["p1"]["positions"][idx,:]
        anglesAct = st["p1"]["angles"][idx,:]
        
        transListAct = calcTransforms(posAct, anglesAct, maxDist, dmetric, uTomoId[i], verbose)
        
        
        
    
    
    
        
        
    
    
    
    

In [7]:
import numpy as np
import multiprocessing as mp
import gc
import sys
#from tom_calcPairTransForm.py import *
def calcTransforms(pos, angles, pruneRad, dmetric, tomoID, verbose):
    #jobList: store three columns: 1.the index of the pair1 in pos_array 2. the index of the pair2 in pos_array
    jobList = np.zeros([pos.shape[0]*pos.shape[0], 2], dtype = np.int)
    zz = 0
    for i in range(pos.shape[0]):
        for ii in range(i+1, pos.shape[0]):
            pos1 = pos[i,:]
            pos2 = pos[ii,:]
            if (np.linalg.norm(pos1 - pos2)) > pruneRad: #discard the pairs with euler distance > pruneRad
                continue
            jobList[zz,0] = i
            jobList[zz,1] = ii
            zz += 1
    jobListN = jobList[0:zz,:]
    jobList = jobListN
    
    transListAct_inner = np.zeros([jobList.shape[0],29], dtype = np.float)
    
    if (verbose == 1):
        #using process bar to show the progress for each process
        
        
        
        
            
    
    
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-7-a1e3b1c357e4>, line 28)

In [ ]:
import multiprocessing
import time

def func(msg):
    return multiprocessing.current_process().name + '-' + msg


pool = multiprocessing.Pool(processes=4) # 创建4个进程
results = []
for i in range(10):
    msg = "hello %d" %(i)
    results.append(pool.apply_async(func, (msg, )))
pool.close()
pool.join() 
print ("Sub-process(es) done.")

for res in results:
    print (res.get())


In [2]:
import numpy as np

In [3]:
sym_id = np.arange(10)

In [4]:
sym_id

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.array_split(range(len(sym_id)),6)[2]

array([4])

In [16]:
0.98958413+0.25524006 + 0.77942732

2.02425151

In [61]:
np.concatenate((np.array([]), np.repeat(["aa"],10)))

'aa'

In [58]:
np.repeat([1],10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
20%10

0

In [41]:
a = np.repeat([1],10)

In [42]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
b = a.reshape(-1,1).reshape(1,-1)[0]

In [57]:
b[[4,5,8,7]]

array([1, 1, 1, 1])

In [62]:
a 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [63]:
import copy

In [65]:
b = copy.deepcopy(a)

In [66]:
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [69]:
c = np.zeros([10,2])
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
c[:,0] = b
c

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [74]:
d = c.astype(np.int)

In [75]:
print(id(d))
print(id(c))

2621210340688
2621189966384


In [81]:
np.tile(['-1:-1','-1:-1'],(10,1))

array([['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1'],
       ['-1:-1', '-1:-1']], dtype='<U5')

In [84]:
a = np.array([1,'-1'])

In [87]:
a.astype(np.int)

array([ 1, -1])

In [88]:
c


array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [89]:
import pandas as pd

In [91]:
pd.DataFrame(c,columns=["a","b"])

a    b
0  1.0  0.0
1  1.0  0.0
2  1.0  0.0
3  1.0  0.0
4  1.0  0.0
5  1.0  0.0
6  1.0  0.0
7  1.0  0.0
8  1.0  0.0
9  1.0  0.0

In [97]:
c=c.astype(np.int)
c[:,1] = np.repeat((-1.9),10)
c

array([[ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1],
       [ 1, -1]])

In [98]:
c = np.zeros([5,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
c[:,1] = np.array([1,1,1,1,1])
c

NameError: name 'c' is not defined

In [101]:
test = pd.DataFrame(c,columns=["a","b","c","d"])
test

a    b    c    d
0  0.0  1.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  1.0  0.0  0.0
3  0.0  1.0  0.0  0.0
4  0.0  1.0  0.0  0.0

In [104]:
test2 = copy.deepcopy(test)
test2.columns = ["y","u","i","o"]
pd.concat([test,test2],axis = 1)

a    b    c    d    y    u    i    o
0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0

In [110]:
test2[["z","g"]] = np.zeros([5,2],np.int)
test2["f"] = ["dsd","fdsd","dfsd","dfsdf","dfsdf"]

In [112]:
test2["f"] = [1,2,3,4,5]
test2

y    u    i    o    z    g  f
0  0.0  1.0  0.0  0.0  0.0  0.0  1
1  0.0  1.0  0.0  0.0  0.0  0.0  2
2  0.0  1.0  0.0  0.0  0.0  0.0  3
3  0.0  1.0  0.0  0.0  0.0  0.0  4
4  0.0  1.0  0.0  0.0  0.0  0.0  5

In [113]:
np.array([1.1,2.1],astype = np.float)

TypeError: 'astype' is an invalid keyword argument for this function

In [114]:
c

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [118]:
i = c.reshape(1,-1)[0]

In [120]:
np.where(i==0)[0]

array([ 0,  2,  3,  4,  6,  7,  8, 10, 11, 12, 14, 15, 16, 18, 19],
      dtype=int64)

In [125]:
a = np.array([],dtype = np.float).reshape(0,4)
np.concatenate((a,c))

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [127]:
test = np.repeat([5],10)

In [128]:
test

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [131]:
yy = np.array([],dtype = np.int)

In [132]:
np.concatenate((yy, test))

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [9]:
import numpy as np
np.repeat([3.2], 10)

array([3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2])

3.4200000000000004

In [13]:
test2["ttt"] = np.repeat([st["p1"]["pixs"][0]], 5)
test2

NameError: name 'test2' is not defined

In [1]:
from tom_sum_rotation import *

In [2]:
 tom_sum_rotation(np.array([[-139,-27,109],[13,-138,-15]]),np.array([[0,0,0],[0,0,0]]),'trans_rot')

s
[[[-0.57548245  0.69610261 -0.42925645]
  [ 0.53294278 -0.07891588 -0.84246322]
  [-0.620316   -0.71359193 -0.32556815]]

 [[-0.57870534  0.79693634  0.17318374]
  [-0.81345582 -0.54890339 -0.19234003]
  [-0.05822162 -0.25218553  0.96592583]]]


(array([-135.3994, -151.2631,   94.4176]),
 array([0., 0., 0.]),
 array([[ 0.65032759, -0.58931175, -0.47935966],
        [ 0.29490705, -0.38567923,  0.87423187],
        [-0.70007418, -0.70990365, -0.07702565]]))

In [3]:
tom_sum_rotation(np.array([[-139,-27,109],[13,-138,-15]]),np.array([[0,0,0],[0,0,0]]),'rot_trans')

[[[-0.57548245  0.69610261 -0.42925645]
  [ 0.53294278 -0.07891588 -0.84246322]
  [-0.620316   -0.71359193 -0.32556815]]

 [[-0.57870534  0.79693634  0.17318374]
  [-0.81345582 -0.54890339 -0.19234003]
  [-0.05822162 -0.25218553  0.96592583]]]


(array([-135.3994, -151.2631,   94.4176]),
 array([0., 0., 0.]),
 array([[ 0.65032759, -0.58931175, -0.47935966],
        [ 0.29490705, -0.38567923,  0.87423187],
        [-0.70007418, -0.70990365, -0.07702565]]))

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a[1:2] = [8]
a

array([1, 8, 3])

In [9]:
a

array([1, 8, 3])

In [11]:
np.array_split(range(len(a)),1)[0]

array([0, 1, 2])

In [13]:
import pandas as pd
tets_dict  = {"a":[1,2,3,4,6],"b":[1.2,3.4,6.5,3.5,6]}
b = pd.DataFrame()
b["a"] = tets_dict["a"]
b["b"] = tets_dict["b"]
b

a    b
0  1  1.2
1  2  3.4
2  3  6.5
3  4  3.5
4  6  6.0

In [15]:
type(b).__name__

'DataFrame'

In [16]:
b

a    b
0  1  1.2
1  2  3.4
2  3  6.5
3  4  3.5
4  6  6.0

In [5]:
header = { }
header["is_loop"] = 1
header["title"] = "data_"
header["fieldNames"] = ['_pairIDX1','_pairIDX2','_pairTomoID',
                              '_pairTransVectX','_pairTransVectY','_pairTransVectZ',
                              '_pairTransAngleZXZPhi', '_pairTransAngleZXZPsi','_pairTransAngleZXZTheta',
                              '_pairInvTransVectX','_pairInvTransVectY','_pairInvTransVectZ',
                              '_pairInvTransAngleZXZPhi', '_pairInvTransAngleZXZPsi','_pairInvTransAngleZXZTheta',
                              '_pairLenTrans','_pairAngDist',
                              '_pairCoordinateX1','_pairCoordinateY1','_pairCoordinateZ1',
                              '_pairAnglePhi1','_pairAnglePsi1','_pairAngleTheta1',
                              '_pairClass1','_pairPsf1',
                               '_pairNeighPlus1','_pairNeighMinus1',
                              '_pairCoordinateX2','_pairCoordinateY2','_pairCoordinateZ2',
                              '_pairAnglePhi2','_pairAnglePsi2','_pairAngleTheta2',
                              '_pairClass2','_pairPsf2',
                               '_pairNeighPlus2','_pairNeighMinus2',
                              '_pairTomoName','_pairPixelSizeAng',
                              '_pairOriPartList',
                              '_pairMaxDist','_pairClass','_pairClassColour','_pairLabel','_pairScore']

In [6]:
f = open('outputName','w')
f.write(header["title"]+"\n")
if header['is_loop'] == 1:
    f.write('loop_'+"\n")
for single_element in header['fieldNames']:
    f.write(single_element+"\n")
f.close()
#write the data body
b.to_csv('outputName',mode = 'a', index=False, header = False,sep = " ")
print("Store the data successfully!")

NameError: name 'b' is not defined

In [7]:
from tom_starread import tom_starread
tom_starread("./ILV")

pairIDX1  pairIDX2  pairTomoID  pairTransVectX  pairTransVectY  \
0             0       124           0       -2.794568      -36.762089   
1             1       116           0       63.233536       69.604912   
2             1       347           0      -11.929689      -81.434464   
3             1       401           0       80.119781        4.118307   
4             1       464           0      -40.256191      -16.972010   
...         ...       ...         ...             ...             ...   
14114     11496     11523          17       -9.338574      -44.829960   
14115     11505     11546          17       -7.487466      -25.933910   
14116     11510     11542          17       43.915955       46.675602   
14117     11516     11532          17      -18.767899      -32.124931   
14118     11538     11543          17       14.477693       80.205330   

       pairTransVectZ  pairTransAngleZXZPhi  pairTransAngleZXZPsi  \
0           61.940060           -135.300293           -152.328705   
1           26.251766             63.312199            -15.287300   
2           22.561117            147.838196            -78.654800   
3           16.491875            156.056198           -101.166801   
4           60.100006            -20.741800             36.979401   
...               ...                   ...                   ...   
14114       54.042545            -51.690399            102.308998   
14115       68.770378           -129.748001            166.091705   
14116       -7.808504             50.860600            -72.942398   
14117       67.225060           -168.368698            161.141205   
14118       33.468113            102.823502             67.809097   

       pairTransAngleZXZTheta  pairInvTransVectX  ...  pairNeighPlus2  \
0                   94.860901          55.442432  ...           -1:-1   
1                   78.544502         -57.013306  ...           -1:-1   
2                   12.916100          77.300484  ...           -1:-1   
3                   95.030800         -21.772114  ...           -1:-1   
4                   78.707802          61.233685  ...           -1:-1   
...                       ...                ...  ...             ...   
14114               86.676498          69.101753  ...           -1:-1   
14115              104.088203          46.897923  ...           -1:-1   
14116               37.481400         -10.547565  ...           -1:-1   
14117               69.479103          22.495615  ...           -1:-1   
14118              118.105103          -3.331626  ...           -1:-1   

       pairNeighMinus2  pairTomoName  pairPixelSizeAng  \
0                -1:-1       101.mrc              3.42   
1                -1:-1       101.mrc              3.42   
2                -1:-1       101.mrc              3.42   
3                -1:-1       101.mrc              3.42   
4                -1:-1       101.mrc              3.42   
...                ...           ...               ...   
14114            -1:-1       118.mrc              3.42   
14115            -1:-1       118.mrc              3.42   
14116            -1:-1       118.mrc              3.42   
14117            -1:-1       118.mrc              3.42   
14118            -1:-1       118.mrc              3.42   

                       pairOriPartList  pairMaxDist  pairClass  \
0      ./all_particles_15-11-2019.star          100         -1   
1      ./all_particles_15-11-2019.star          100         -1   
2      ./all_particles_15-11-2019.star          100         -1   
3      ./all_particles_15-11-2019.star          100         -1   
4      ./all_particles_15-11-2019.star          100         -1   
...                                ...          ...        ...   
14114  ./all_particles_15-11-2019.star          100         -1   
14115  ./all_particles_15-11-2019.star          100         -1   
14116  ./all_particles_15-11-2019.star          100         -1   
14117  ./all_particles_15-11-2019.star          100         -1   
1

In [12]:
(0.7060-0.6948)**2 + (0.046-0.0344)**2

0.0002599999999999997

In [10]:
import numpy as np

In [13]:
np.sqrt(0.0002599999999999997)

0.01612451549659709

In [14]:
%history

star_data = tom_starread("./all_particles_15-11-2019.star")
star_data
from  tom_starread import tom_starread
from tom_extractData import tom_extractData
star_data = tom_starread("./all_particles_15-11-2019.star")
star_data
st = tom_extractData(star_data,0)
header = { }
header["is_loop"] = 1
header["title"] = "data_"
header["fieldNames"] = ['_pairIDX1','_pairIDX2','_pairTomoID',
                              '_pairTransVectX','_pairTransVectY','_pairTransVectZ',
                              '_pairTransAngleZXZPhi', '_pairTransAngleZXZPsi','_pairTransAngleZXZTheta',
                              '_pairInvTransVectX','_pairInvTransVectY','_pairInvTransVectZ',
                              '_pairInvTransAngleZXZPhi', '_pairInvTransAngleZXZPsi','_pairInvTransAngleZXZTheta',
                              '_pairLenTrans','_pairAngDist',
                              '_pairCoordinateX1','_pairCoordinateY1','_pairCoordinateZ1',
                              '_pairAnglePhi1','_pairAnglePsi1','_

In [15]:
np.sqrt(2**2*3)

3.4641016151377544

In [17]:
a = np.array([1,2,3])
a.shape[0]

3